add StockApiTest
b2etw/event-2020-1-java pull request #12
Opened 2020-03-22 12:25 UTC by JerryLin0920

# Checklist:
- [v] My code follows the style guidelines of this project (IntelliJ Default)
- [v] My changes generate no new warnings
- [v] I have performed a self-review of my own code
- [v] I have commented my code, particularly in hard-to-understand areas
- [v] I have added tests that prove my fix is effective or that my feature works
- [v] New and existing unit tests pass locally with my changes

2020-03-22 17:28 UTC, Jian-Min-Huang requested changes
再請你看看喔 😏

2020-03-22 17:28 UTC, Jian-Min-Huang commented on pom.xml
> +
加 library 是沒問題的，不過我好奇為什麼不直接用純的 RestTemplate 就好，還是你有SSL安全性的考量呢？

2020-03-22 17:28 UTC, Jian-Min-Huang commented on pom.xml
> +
另外，你的 StockApiVo 和 StockApiMsgVo 要不要考慮用一下 Lombok 呢，可以讓語法更簡潔

```
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <optional>true</optional>
</dependency>
```

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/Event20201JavaApplication.java
>  @ServletComponentScan
上面有import可是下面沒有東西，你這邊是不是漏推了什麼？

例如 ObjectMapper 的 @Bean ?

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/common/CommonUtils.java
> +}
因為我們的專案是 Spring，正常就不會創建靜態類別跟方法，建議稍微調整一下換成Spring @Bean

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/stock/StockRouter.java
> +  final public static String API_URL = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=%s";
這兩個為什麼不能合成同一個呢？
```suggestion
  final public static String API_URL = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=tse_%s.tw";
```

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/stock/StockRouter.java
> +          new URI(String.format(StockRouter.API_URL, String.format(StockRouter.EX_CH_TEMP, "2330"))));
承上
```suggestion
      requestEntity = new RequestEntity<>(HttpMethod.GET, new URI(String.format(StockRouter.API_URL, "2330")));
```

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/stock/vo/StockApiMsgVo.java
> +}
建議採用 Lombok

2020-03-22 17:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/stock/vo/StockApiVo.java
> +}
建議採用 Lombok

2020-03-23 01:55 UTC, JerryLin0920 commented on pom.xml
> +
1.有使用api是https的資源，找到trust的方法有使用到這個dependency
2.其實原本就有使用lombok,但是考量到可能並不是所有人都有裝插件，所以才沒有使用

2020-03-23 01:55 UTC, JerryLin0920 commented on src/main/java/tw/b2e/Event20201JavaApplication.java
>  @ServletComponentScan
當初這裡有用一個bean，但是刪除後忘記處理掉..

2020-03-23 01:57 UTC, JerryLin0920 commented on src/main/java/tw/b2e/common/CommonUtils.java
> +}
沒有弄成一個bean是因為restTemplate之前使用上有遇過一個問題，如果重複使用同一個，使用到一定次數後會錯誤(有點忘記是什麼，只記得是連線相關的錯誤)，所以後來在使用的時候都是弄成會重新new restTemplate

2020-03-23 02:00 UTC, JerryLin0920 commented on src/main/java/tw/b2e/stock/StockRouter.java
> +  final public static String API_URL = "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch=%s";
考量這個api可能會有台股以外的參數(非tse_xxx.tw,例：IBM.US),所以才沒有合併成一個，是可以一開始就用成一個沒錯

2020-03-23 02:45 UTC, JerryLin0920 commented on src/main/java/tw/b2e/stock/vo/StockApiVo.java
> +}
同 [第二點](https://github.com/b2etw/event-2020-1-java/pull/12#pullrequestreview-379027364)

2020-03-23 02:45 UTC, JerryLin0920 commented on src/main/java/tw/b2e/stock/vo/StockApiMsgVo.java
> +}
同 [第二點](https://github.com/b2etw/event-2020-1-java/pull/12#pullrequestreview-379027364)

2020-03-23 06:37 UTC, Jian-Min-Huang commented on pom.xml
> +
1. http client 我覺得ok沒問題了
2. lombok是趨勢，值得一學，這次的目標對象設定在IntelliJ IDEA，我想裝plugin是沒問題的

2020-03-23 06:49 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/common/CommonUtils.java
> +}
因為我們是社群性質的專案，所以這邊就不太深究。

不過寫法上這樣還是不太優，記得要找到那個錯誤修正喔

2020-03-23 06:50 UTC, Jian-Min-Huang requested changes
lombok加一加我就覺得可以惹

2020-03-23 11:54 UTC, yenhsunli commented on pom.xml
> +
初次看到lombok 我也來練練

2020-03-23 12:07 UTC, frankiego requested changes
review完，跟Vincent意見差不多，補個Lombok即可

2020-03-23 15:11 UTC, JerryLin0920 commented on src/main/java/tw/b2e/common/CommonUtils.java
> +}
已調整restTemplate，有嘗試重現錯誤不過無法重現，可能是當時環境問題導致，所以先調整成註冊Bean的用法

2020-03-23 15:11 UTC, JerryLin0920 commented on pom.xml
> +
已改用lombok

2020-03-24 11:13 UTC, Jian-Min-Huang approved these changes
LGTM

2020-03-24 11:34 UTC, frankiego approved these changes
LGTM

2020-03-25 08:00 UTC, merged