[Feature]實作解析參數與轉導至對應的Service
b2etw/event-2020-1-java pull request #18
Opened 2020-04-09 04:39 UTC by Naihua-TW

# Checklist:
- [ ] My code follows the style guidelines of this project (IntelliJ Default)
- [ ] My changes generate no new warnings
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-04-11 14:37 UTC, Jian-Min-Huang requested changes
主要是Lombok 😆

2020-04-11 14:37 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/receipt/ReceiptRouter.java
> +
@Slf4j

可以考慮學一下Lombok，算是挺好的東西

2020-04-11 14:37 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/receipt/vo/CommandParam.java
> +
same problem, how about Lombok 😏

2020-04-12 03:01 UTC, Naihua-TW commented on src/main/java/tw/b2e/receipt/ReceiptRouter.java
> +
已改為lombok風格，再麻煩Review 謝謝

2020-04-12 03:02 UTC, Naihua-TW commented on src/main/java/tw/b2e/receipt/vo/CommandParam.java
> +
已改為lombok風格，再麻煩Review 謝謝

2020-04-13 09:03 UTC, Jian-Min-Huang approved these changes
LGTM

2020-04-13 09:08 UTC, Jian-Min-Huang commented
因為已經衝突到無法解，直接關掉重做PR可能會好一點

2020-04-13 09:08 UTC, closed without merging