PTT 看板清單
b2etw/event-2020-1-java pull request #25
Opened 2020-04-25 10:26 UTC by jerry80409

# Checklist:
- [ ] My code follows the style guidelines of this project (IntelliJ Default)
- [ ] My changes generate no new warnings
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2020-04-28 14:22 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/news/CommandService.java
> +          Arrays.asList(Arrays.copyOfRange(commands, 2, commands.length)));
你長度設多短啊，這個怎麼會換行了XDD

2020-04-28 14:24 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/news/PttCrawlerService.java
> +  // todo - I will refactor it. 人肉爬蟲 XD
大家都看到惹

2020-04-28 14:28 UTC, Jian-Min-Huang commented on src/main/java/tw/b2e/news/README.md
> +* COVID-19 趨勢與資訊
這個要不要考慮移去外面

2020-04-28 14:30 UTC, Jian-Min-Huang requested changes
我覺得你寫code品味蠻好的

2020-05-04 03:14 UTC, jerry80409 commented on src/main/java/tw/b2e/news/PttCrawlerService.java
> +  // todo - I will refactor it. 人肉爬蟲 XD
😂

2020-05-04 03:15 UTC, jerry80409 commented
@Jian-Min-Huang 謝謝, 我還在努力學習中...

2020-05-04 03:16 UTC, jerry80409 commented on src/main/java/tw/b2e/news/README.md
> +* COVID-19 趨勢與資訊
README.md 的部分可否協助我整理, 我不太確定整合到 README.md 的排版, 麻煩了, 感謝

2020-05-04 03:18 UTC, jerry80409 commented on src/main/java/tw/b2e/news/CommandService.java
> +          Arrays.asList(Arrays.copyOfRange(commands, 2, commands.length)));
自己的壞習慣 XD

2020-05-14 16:12 UTC, merged